[package]
name = "all-in-icmp"
version = "1.1.0"
edition = "2024"

[dependencies]
nfq = "*"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3 # Optimize for speed.
